# Config settings
title: Jekyll Redirect Layout Demo
baseurl: "/jekyll-redirect-layout"

# Redirect settings
collections:
  redirects:
    output: true

defaults:
  -
    scope:
      type: redirects
    values:
      layout: redirect

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
